### PR TITLE
Do not depend on http status code

### PR DESCRIPTION
**Pull request by Frozenlock**
Fix for #15.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks for the PR, and apologies for the delay in reviewing it! Can you add a test for this change, and can you change the commit message to:

```
Add refresh injection for error responses

Fixes #15.
```

**Comment by Frozenlock** [comment]
Ok it's done.

Should I change the project version, or you'll do it before deploying?

**Comment by weavejester** [comment]
Perfect, thanks! I'll merge it in later tonight. Don't change the project version; I'll do that on release.

**Comment by Frozenlock** [comment]
Any ETA on when the next version will be released?

**Comment by weavejester** [comment]
Ah, whoops! Sorry, this task got lost in my inbox somehow. I'll release a new version now.

**Pull request merged**
